export const FETCH_PRODUCT_LISTS = 'FETCH_PRODUCT_LISTS';
export const PRODUCT_LISTS_SUCCESS = 'PRODUCT_LISTS_SUCCESS';
export const PRODUCT_LISTS_FAIL = 'PRODUCT_LISTS_FAIL';

export const PRODUCT_DETAILS_FETCH = 'PRODUCT_DETAILS_FETCH';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';
export const CLEAR_PRODUCT_DETAILS = 'CLEAR_PRODUCT_DETAILS';
